### ISSUE TITLE
Remove file \Models\Database.cs

### ISSUE THREAD

**Issue by administer** [kendriya/QuizMvc5#12]
This file is being replaced by QuizDatabase.cs

**Comment by rajneeshchhawari** [comment]
i am using this file in complete project instead if QuizDatabase.cs so can't remove it.

**Comment by administer** [comment]
All the functionality must be derived from QuizDatabase.cs. Database class is reserved in MVC5

**Comment by rajneeshchhawari** [comment]
I will change at the end of project components
