### ISSUE TITLE
Replace contents from the trunk

### ISSUE THREAD

**Issue by administer** [kendriya/QuizMvc5#13]
\Scripts\_references.js
\Scripts\bootstrap.js

Remove the following files:
Scripts\angular.js
Scripts\angular.min.js
Scripts\angular.min.js.map
Scripts\angular-mocks.js
Scripts\directives.js
Scripts\jquery.cleditor.js
Scripts\jquery.cleditor.min.js
Scripts\jquery.min.js
Scripts\QuizictionaryAngularApp.js

**Comment by rajneeshchhawari** [comment]
removed
