### ISSUE TITLE
Quiz Creation error is showing as red on the bottom, but it should show as a popup.

### ISSUE THREAD

**Issue by psaurabh** [kendriya/QuizMvc5#18]
![image](https://cloud.githubusercontent.com/assets/7782624/10504457/a05fb1f8-72ce-11e5-96fc-30597f94cbb2.png)

**Comment by rajneeshchhawari** [comment]
Now its showing in popup and you can see in next update

**Comment by psaurabh** [comment]
It is not working if title is missed

**Comment by rajneeshchhawari** [comment]
done
