### ISSUE TITLE
Twitter Login not working

### ISSUE THREAD

**Issue by sunnysood** [kendriya/QuizMvc5#19]
Steps
1. Register with Twitter account

Expected Results
User should be able to login successfully

Actual Results
There is an exception

**Comment by rajneeshchhawari** [comment]
Now its working with all social links.

**Comment by sunnysood** [comment]
Twitter still does not work

![image](https://cloud.githubusercontent.com/assets/10386747/10568563/f97ef520-75e7-11e5-9daf-8a9c81eea960.png)

**Comment by rajneeshchhawari** [comment]
now i have updated code. so please check again
