### ISSUE TITLE
New Quiz Creation error

### ISSUE THREAD

**Issue by psaurabh** [kendriya/QuizMvc5#29]
When added html text in quiz detail then the following error

![image](https://cloud.githubusercontent.com/assets/7782624/10504653/cff5ea98-72d0-11e5-97fc-be1d0094cb0e.png)

**Comment by rajneeshchhawari** [comment]
Problem is if user select the same image for multipal question then in the controller will move to staging to package/quiz folder. and if one image is select for multipal question then file not exists error at the time of moving images from staging to package folder.

**Comment by rajneeshchhawari** [comment]
i have solve all design issue but not backend part.
