### ISSUE TITLE
Start quiz and quiz detail links on package detail screen point back to package detail

### ISSUE THREAD

**Issue by administer** [kendriya/QuizMvc5#30]

**Comment by rajneeshchhawari** [comment]
Now its showing quiz details in popup and on click of start button user can start quiz of current package.

**Comment by administer** [comment]
Still not resolved, when looking at the package details, Start Quiz link still shows the package details

**Comment by rajneeshchhawari** [comment]
now i have updated code so please check again

**Comment by administer** [comment]
Quiz package details, when link "View Detail" and take quiz, the dialog box does not go away by itself.

**Comment by rajneeshchhawari** [comment]
done
