### ISSUE TITLE
Package Sharing with Email is not working

### ISSUE THREAD

**Issue by psaurabh** [kendriya/QuizMvc5#34]
Package Sharing with Email is not working

![image](https://cloud.githubusercontent.com/assets/7782624/10505109/77bece24-72d7-11e5-92cc-676054d64b60.png)

**Comment by rajneeshchhawari** [comment]
Sharing will be work in only published website and waiting for backend work of Email share.

**Comment by rajneeshchhawari** [comment]
Backend Code in MarketPlace controller is missing.
