### ISSUE TITLE
When submitting quiz, the dialog button says to send for approval. Options on that dialog do not work and the current quiz is still displayed.

### ISSUE THREAD

**Issue by administer** [kendriya/QuizMvc5#35]
Following this, user is still able to create more questions on the same quiz.

**Comment by rajneeshchhawari** [comment]
I will link that buttons in popup in next component so thats why is still pending

**Comment by psaurabh** [comment]
Controller name: PackageSubmitForApproval

**Comment by rajneeshchhawari** [comment]
done

**Comment by rajneeshchhawari** [comment]
This is next components parts so will be solve in next phase
