### ISSUE TITLE
Cannot unhide the clock

### ISSUE THREAD

**Issue by sunnysood** [kendriya/QuizMvc5#38]
Once you click hide clock, it goes away but there is not way to unhide it

![image](https://cloud.githubusercontent.com/assets/10386747/10568665/574e3c8c-75e9-11e5-826a-7a8d454d8d07.png)

**Comment by rajneeshchhawari** [comment]
now its working fine

**Comment by sunnysood** [comment]
That bug is fixed but now it does not show the hide button anymore

![image](https://cloud.githubusercontent.com/assets/10386747/10655378/1561a07e-7842-11e5-9b32-c907ac25afb0.png)

**Comment by rajneeshchhawari** [comment]
done
