### ISSUE TITLE
When a Quiz is submitted the submit button must be disabled and the running clock must  stop.

### ISSUE THREAD

**Issue by psaurabh** [kendriya/QuizMvc5#39]
When a Quiz is submitted the submit button must be disabled and the running clock must  stop.
Right now you can take the quiz multiple times and when reviewing the answers the icon are showing multiple times.

Quiz can be submitted any number of times
-----------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/7782624/10655179/37801084-7840-11e5-8301-ad64a3807ec7.png)

![image](https://cloud.githubusercontent.com/assets/7782624/10655198/6fa90b5a-7840-11e5-8919-fd34c2fd18e4.png)

![image](https://cloud.githubusercontent.com/assets/7782624/10655208/89103c4e-7840-11e5-8a22-75cd912e3cb2.png)

**Comment by rajneeshchhawari** [comment]
done
