### ISSUE TITLE
Modify file Content\External\admindesigns\theme\assets\skin\default_skin\css\theme.css to use admindesigns standard css

### ISSUE THREAD

**Issue by administer** [kendriya/QuizMvc5#4]
Lines 

body.external-page.external-alt .login-links a {
  color: #4a89dc;
  font-weight: 600;
}
body.external-page.external-alt .login-links a.active {
  color: #555;
}

should be changed to

body.external-page.external-alt .login-links a {
  color: #555;
  font-weight: 600;
}
body.external-page.external-alt .login-links a.active {
  color: #4a89dc;
}

**Comment by rajneeshchhawari** [comment]
done
