### ISSUE TITLE
Package cannot be created with html text as description

### ISSUE THREAD

**Issue by psaurabh** [kendriya/QuizMvc5#41]
![image](https://cloud.githubusercontent.com/assets/7782624/10655749/a508ad78-7845-11e5-8cdb-0c65032bc1d7.png)

**Comment by rajneeshchhawari** [comment]
This Issue i have already discuss in meeting, So please correct the controller to escape the Editor value.

**Comment by psaurabh** [comment]
It not reaching controller.

**Comment by rajneeshchhawari** [comment]
done
